version: '3.5'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/etc/nginx/conf.d:ro
    networks:
      - external_proxy-network
    ports:
      - "80:80"

networks:
  external_proxy-network:
    driver: bridge
    name: external_proxy-network
