apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}
spec:
  type: NodePort
  selector:
    app: {{ app_name }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{ port }}
      targetPort: {{ port }}
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007
